from __future__ import annotations

import shutil
import subprocess
from datetime import timedelta
from pathlib import Path
from typing import Any


def _safe_text(value: Any, default: str = "") -> str:
    if value is None:
        return default
    text = str(value).strip()
    return text if text else default


def _seconds_to_srt(seconds: float) -> str:
    total_ms = max(int(seconds * 1000), 0)
    td = timedelta(milliseconds=total_ms)
    days = td.days
    seconds_in_day = td.seconds + days * 24 * 3600
    hours = seconds_in_day // 3600
    minutes = (seconds_in_day % 3600) // 60
    secs = seconds_in_day % 60
    millis = td.microseconds // 1000
    return f"{hours:02d}:{minutes:02d}:{secs:02d},{millis:03d}"


def _build_copy_map(copywriting_items: list[dict[str, Any]]) -> dict[str, str]:
    result: dict[str, str] = {}
    for row in copywriting_items:
        if not isinstance(row, dict):
            continue
        listing_id = _safe_text(row.get("listing_id"))
        if not listing_id:
            continue
        variants = row.get("variants")
        if isinstance(variants, list) and variants:
            best = _safe_text(variants[0])
            if best:
                result[listing_id] = best
                continue
        title = _safe_text(row.get("title"))
        if title:
            result[listing_id] = title
    return result


def build_video_storyboard(
    clean_rows: list[dict[str, Any]],
    copywriting_items: list[dict[str, Any]] | None = None,
    *,
    template: str = "default",
    max_items: int = 8,
    intro_seconds: float = 2.0,
    card_seconds: float = 2.5,
    outro_seconds: float = 2.0,
) -> dict[str, Any]:
    top_rows = clean_rows[: max(1, int(max_items))]
    copy_map = _build_copy_map(copywriting_items or [])

    cursor = 0.0
    shots: list[dict[str, Any]] = [
        {
            "type": "intro",
            "start": round(cursor, 3),
            "end": round(cursor + intro_seconds, 3),
            "duration": round(intro_seconds, 3),
            "headline": "City Property Highlights",
            "subtitle": "Auto-generated by house workflow",
        }
    ]
    cursor += intro_seconds

    for row in top_rows:
        listing_id = _safe_text(row.get("listing_id"), f"listing-{len(shots)}")
        district = _safe_text(row.get("district"), "unknown")
        community = _safe_text(row.get("community"), "community")
        layout = _safe_text(row.get("layout"), "layout")
        price = row.get("total_price_wan")
        area = row.get("area_sqm")
        headline = f"{district} | {community}"
        subtitle = f"{layout} | {area} sqm | {price} wan"
        narrative = copy_map.get(listing_id, _safe_text(row.get("title"), headline))
        shots.append(
            {
                "type": "listing",
                "listing_id": listing_id,
                "start": round(cursor, 3),
                "end": round(cursor + card_seconds, 3),
                "duration": round(card_seconds, 3),
                "headline": headline,
                "subtitle": subtitle,
                "narrative": narrative,
            }
        )
        cursor += card_seconds

    shots.append(
        {
            "type": "outro",
            "start": round(cursor, 3),
            "end": round(cursor + outro_seconds, 3),
            "duration": round(outro_seconds, 3),
            "headline": "Contact Agent",
            "subtitle": "Generated by OpenClaw property workflow",
        }
    )
    cursor += outro_seconds

    return {
        "template": template,
        "generated_item_count": len(top_rows),
        "total_duration_seconds": round(cursor, 3),
        "shots": shots,
    }


def render_storyboard_srt(storyboard: dict[str, Any], output_path: Path) -> Path:
    shots = storyboard.get("shots", [])
    rows: list[str] = []
    index = 1
    for shot in shots:
        if not isinstance(shot, dict):
            continue
        start = float(shot.get("start", 0.0))
        end = float(shot.get("end", 0.0))
        if end <= start:
            continue
        headline = _safe_text(shot.get("headline"))
        subtitle = _safe_text(shot.get("subtitle"))
        narrative = _safe_text(shot.get("narrative"))
        text = " | ".join([part for part in [headline, subtitle, narrative] if part])
        if not text:
            continue
        rows.append(str(index))
        rows.append(f"{_seconds_to_srt(start)} --> {_seconds_to_srt(end)}")
        rows.append(text)
        rows.append("")
        index += 1

    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text("\n".join(rows), encoding="utf-8")
    return output_path


def generate_template_video(
    storyboard: dict[str, Any],
    output_path: Path,
    *,
    ffmpeg_bin: str = "ffmpeg",
    captions_path: Path | None = None,
    template: str = "default",
    bgm_path: Path | None = None,
    bgm_volume: float = 0.18,
    width: int = 720,
    height: int = 1280,
    background_color: str = "0x111827",
) -> dict[str, Any]:
    duration = max(float(storyboard.get("total_duration_seconds", 0.0)), 3.0)
    output_path = output_path.resolve()
    output_path.parent.mkdir(parents=True, exist_ok=True)

    ffmpeg_path = _resolve_ffmpeg_path(ffmpeg_bin)
    if not ffmpeg_path:
        return {
            "status": "skipped_ffmpeg_missing",
            "ffmpeg_bin": ffmpeg_bin,
            "output_video": str(output_path),
            "duration_seconds": duration,
            "error": "ffmpeg executable not found",
        }

    command = [
        ffmpeg_path,
        "-y",
        "-f",
        "lavfi",
        "-i",
        f"color=c={background_color}:s={width}x{height}:d={duration:.3f}",
    ]

    resolved_bgm_path = bgm_path.resolve() if bgm_path and bgm_path.exists() else None
    bgm_used = bool(resolved_bgm_path)
    if resolved_bgm_path:
        command.extend(["-stream_loop", "-1", "-i", str(resolved_bgm_path)])
    else:
        command.extend(
            [
                "-f",
                "lavfi",
                "-i",
                "anullsrc=channel_layout=stereo:sample_rate=44100",
            ]
        )

    command.append("-shortest")

    filter_chain = _build_video_filter_chain(template=template, captions_path=captions_path)
    if filter_chain:
        command.extend(["-vf", filter_chain])
    if bgm_used:
        safe_volume = max(0.0, min(float(bgm_volume), 1.0))
        command.extend(["-af", f"volume={safe_volume:.2f}"])

    command.extend(
        [
            "-c:v",
            "libx264",
            "-pix_fmt",
            "yuv420p",
            "-c:a",
            "aac",
            "-b:a",
            "128k",
            str(output_path),
        ]
    )

    run = _run_ffmpeg(command)
    captions_embedded = "subtitles=" in (filter_chain or "") and run.returncode == 0
    caption_warning = ""
    if run.returncode != 0 and captions_embedded is False and "subtitles=" in (filter_chain or ""):
        fallback_command = [part for part in command]
        vf_index = fallback_command.index("-vf")
        fallback_filter = _build_video_filter_chain(template=template, captions_path=None)
        if fallback_filter:
            fallback_command[vf_index + 1] = fallback_filter
        else:
            del fallback_command[vf_index : vf_index + 2]
        fallback_run = _run_ffmpeg(fallback_command)
        if fallback_run.returncode == 0:
            run = fallback_run
            captions_embedded = False
            caption_warning = "subtitle embedding failed, generated video without burned captions"
            command = fallback_command

    if run.returncode != 0:
        return {
            "status": "failed",
            "ffmpeg_bin": ffmpeg_path,
            "output_video": str(output_path),
            "duration_seconds": duration,
            "command": command,
            "returncode": run.returncode,
            "error": (run.stderr or run.stdout or "").strip()[-1000:],
        }

    return {
        "status": "success",
        "ffmpeg_bin": ffmpeg_path,
        "output_video": str(output_path),
        "duration_seconds": duration,
        "template": template,
        "bgm_used": bgm_used,
        "bgm_path": str(resolved_bgm_path) if resolved_bgm_path else "",
        "captions_embedded": captions_embedded,
        "caption_warning": caption_warning,
        "command": command,
    }


def _resolve_ffmpeg_path(ffmpeg_bin: str) -> str | None:
    ffmpeg_path = shutil.which(ffmpeg_bin)
    if ffmpeg_path:
        return ffmpeg_path

    try:
        import imageio_ffmpeg
    except Exception:
        return None

    try:
        return imageio_ffmpeg.get_ffmpeg_exe()
    except Exception:
        return None


def _build_subtitle_filter(captions_path: Path | None) -> str | None:
    if captions_path is None:
        return None
    path = captions_path.resolve()
    if not path.exists():
        return None
    filter_path = path.as_posix().replace(":", r"\:").replace("'", r"\'")
    return f"subtitles='{filter_path}'"


def _build_video_filter_chain(*, template: str, captions_path: Path | None) -> str:
    filters: list[str] = []
    if template == "default":
        filters.extend(
            [
                "eq=brightness=0.02:contrast=1.08:saturation=1.12",
                "drawbox=x=0:y=0:w=iw:h=180:color=black@0.30:t=fill",
                "drawbox=x=0:y=ih-220:w=iw:h=220:color=black@0.34:t=fill",
            ]
        )
    elif template == "clean":
        filters.append("eq=brightness=0.01:contrast=1.04:saturation=1.05")
    subtitle_filter = _build_subtitle_filter(captions_path)
    if subtitle_filter:
        filters.append(subtitle_filter)
    return ",".join(filters)


def _run_ffmpeg(command: list[str]) -> subprocess.CompletedProcess[str]:
    return subprocess.run(
        command,
        check=False,
        capture_output=True,
        text=True,
    )
