from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Any

import requests


def _extract_ticket(payload: dict[str, Any]) -> str:
    login = payload.get("login")
    if not isinstance(login, dict):
        return ""
    service_ticket = login.get("serviceTicket")
    if not isinstance(service_ticket, dict):
        return ""
    ticket = service_ticket.get("id")
    return str(ticket).strip() if ticket else ""


def _build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description="Exchange A+ serviceTicket into web cookies")
    parser.add_argument(
        "--login-result",
        default=str(Path(__file__).resolve().parents[1] / "runtime" / "aplus_qr_login_result.json"),
        help="Path to login result JSON generated by aplus_qr_login_server.py",
    )
    parser.add_argument(
        "--saas-cas-url",
        default="https://saas.a.ke.com/cas",
        help="CAS URL used for service ticket exchange",
    )
    parser.add_argument(
        "--output",
        default=str(Path(__file__).resolve().parents[1] / "runtime" / "aplus_session_cookies.json"),
        help="Output cookie json path",
    )
    parser.add_argument(
        "--timeout",
        type=int,
        default=20,
        help="HTTP timeout seconds",
    )
    return parser


def main() -> int:
    args = _build_parser().parse_args()
    login_result_path = Path(args.login_result).resolve()
    if not login_result_path.exists():
        raise FileNotFoundError(f"login result not found: {login_result_path}")

    payload = json.loads(login_result_path.read_text(encoding="utf-8"))
    ticket = _extract_ticket(payload)
    if not ticket:
        raise ValueError("serviceTicket.id not found in login result")

    session = requests.Session()
    url = f"{args.saas_cas_url}?ticket={ticket}"
    response = session.get(url, allow_redirects=True, timeout=args.timeout)
    response.raise_for_status()

    cookies = [{"name": c.name, "value": c.value, "domain": c.domain, "path": c.path} for c in session.cookies]
    output_path = Path(args.output).resolve()
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(
        json.dumps(
            {
                "ticket": ticket,
                "exchange_url": url,
                "status_code": response.status_code,
                "final_url": response.url,
                "cookies": cookies,
            },
            ensure_ascii=False,
            indent=2,
        ),
        encoding="utf-8",
    )
    print(f"[aplus-ticket] exchanged, cookies={len(cookies)} -> {output_path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
