from __future__ import annotations

import argparse
import json
import os
import sys
from datetime import datetime
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parents[1]
if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))

from property_workflow.collectors.aplus_endpoint_discovery import discover_aplus_endpoints, save_discovery_payload


def _build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description="Discover A+ business hosts and listing endpoint candidates")
    parser.add_argument(
        "--resources-js-dir",
        default=str(
            Path(os.environ.get("APPDATA", str(Path.home() / "AppData/Roaming")))
            / "A+"
            / "resources"
            / "app"
            / "js"
        ),
        help="A+ resources/app/js directory",
    )
    parser.add_argument(
        "--local-storage-dump",
        default=str(PROJECT_ROOT / "runtime" / "local_storage_log_dump.txt"),
        help="Path to local storage log dump",
    )
    parser.add_argument(
        "--output",
        default=str(PROJECT_ROOT / "runtime" / "aplus_endpoint_discovery.json"),
        help="Output json path",
    )
    parser.add_argument(
        "--live-scan-file",
        default=str(PROJECT_ROOT / "runtime" / "aplus_live_api_scan.json"),
        help="Optional live scan json generated by aplus_live_api_scan.py",
    )
    parser.add_argument(
        "--click-capture-file",
        default=str(PROJECT_ROOT / "runtime" / "aplus_click_capture.json"),
        help="Optional CDP capture json generated by aplus_cdp_capture.js",
    )
    parser.add_argument(
        "--extra-scan-file",
        action="append",
        default=[],
        help="Extra text/js files to include in host scan",
    )
    parser.add_argument(
        "--code-cache-js-dir",
        default=str(Path(os.environ.get("APPDATA", str(Path.home() / "AppData/Roaming"))) / "A+" / "Code Cache" / "js"),
        help="A+ Code Cache js directory (optional)",
    )
    parser.add_argument(
        "--code-cache-max-files",
        type=int,
        default=120,
        help="Max code-cache files appended into scan (latest by mtime)",
    )
    return parser


def _pick_code_cache_files(code_cache_js_dir: Path, max_files: int) -> list[Path]:
    if not code_cache_js_dir.exists() or max_files <= 0:
        return []
    rows: list[Path] = []
    for path in code_cache_js_dir.glob("*"):
        if not path.is_file():
            continue
        # Skip tiny marker files to reduce scan noise.
        if path.stat().st_size < 512:
            continue
        rows.append(path)
    rows.sort(key=lambda p: p.stat().st_mtime, reverse=True)
    return rows[:max_files]


def main() -> int:
    args = _build_parser().parse_args()

    resources_js_dir = Path(args.resources_js_dir).resolve()
    local_storage_dump = Path(args.local_storage_dump).resolve()
    output_path = Path(args.output).resolve()
    extra_scan_files = [Path(p).resolve() for p in args.extra_scan_file]
    live_scan_file = Path(args.live_scan_file).resolve()
    if live_scan_file.exists():
        extra_scan_files.append(live_scan_file)
    click_capture_file = Path(args.click_capture_file).resolve()
    if click_capture_file.exists():
        extra_scan_files.append(click_capture_file)
    code_cache_js_dir = Path(args.code_cache_js_dir).resolve()
    extra_scan_files.extend(_pick_code_cache_files(code_cache_js_dir, max_files=args.code_cache_max_files))

    payload = discover_aplus_endpoints(
        resources_js_dir=resources_js_dir,
        local_storage_dump=local_storage_dump,
        extra_scan_files=extra_scan_files,
    )
    payload["generated_at"] = datetime.now().isoformat(timespec="seconds")
    payload["resources_js_dir"] = str(resources_js_dir)
    payload["local_storage_dump"] = str(local_storage_dump)
    payload["code_cache_js_dir"] = str(code_cache_js_dir)

    save_discovery_payload(output_path, payload)

    hosts = payload.get("hosts", [])
    endpoint_candidates = payload.get("endpoint_candidates", [])
    print(f"[aplus-endpoint-finder] hosts={len(hosts)}, endpoint_candidates={len(endpoint_candidates)}")
    print(f"[aplus-endpoint-finder] output -> {output_path}")
    for row in hosts[:8]:
        print(f"- host={row.get('host')} score={row.get('score')}")
    for row in endpoint_candidates[:8]:
        print(f"- candidate={row.get('method')} {row.get('endpoint')}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
